use crate::result::report;

report!(Errors(E) {
    InvalidUtf8Character[001] => "invalid UTF-8 character",
    InvalidCharacter[002] => "Unknown character encountered",
    InvalidNumericLiteral[003] => "invalid numeric literal",
    InvalidStringLiteral[004] => "invalid string literal",
    UnclosedBlockComment[005] => "unclosed block comment",
    UnexpectedEof[006] => "unxpected end",
    UnexpectedToken[007] => "unexpected token",
    InvalidNodeAddress[008] => "invalid node address",
    InvalidNodeName[009] => "invalid node name",
    InvalidLabelName[010] => "invalid label name",
    UnexpectedWhitespace[011] => "unexpected whitespace or comment",
    MissingParentheses[012] => "missing parentheses",
    UnmatchedDelimiter[013] => "unmatched delimiter",
    InvalidTernaryOperator[014] => "invalid ternary operator",
    InvalidNodePath[015] => "invalid node path",
    InvalidReference[016] => "invalid reference",
    InvalidExpression[017] => "invalid expression",
    UnknownCompilerDirective[018] => "unknown compiler directive",
    NestedRootNode[019] => "nested root node",
    DuplicitLabel[021] => "re-defined label",
    NestedReferenceNode[022] => "nested reference node",
    InvalidLabelTarget[023] => "invalid label target",
    InvalidOmitTarget[024] => "invalid omit-if-no-ref target",
    InvalidNodePlacement[026] => "invalid node placement",
    DeletePropertyOnRoot[027] => "delete property on root",
    ContentBeforeHeader[028] => "content before dts header",
    NestedMemreserve[029] => "nested memreserve directive",
    UnexpectedDtsHeader[030] => "unexpected `dts-v1` header",
    PropertyAfterSubnodes[031] => "property after subnodes",
    ScopeRedefinition[032] => "scope content redefinition",
    DeleteInSameScope[033] => "delete in the same scope",
    ChainedOmits[034] => "chained `omit-if-no-ref` directives",
    NestedReferencedNodeDelete[035] => "nested node delete with a reference",
    StandardNodeOutsideScope[036] => "standard node outside scope",
    PropertyOutsideScope[037] => "property outside scope",
    RejectedInclude[038] => "includer rejected an include",
    DeleteTargetNotFound[039] => "delete target not found",
    NotANodeLabel[040] => "label does point to a node",
    UnknownLabel[041] => "unknown label name",
    NodeNotFound[042] => "node not found in scope",
    IncludeRejected[043] => "include rejected",
    DeleteOnRoot[044] => "delete node on root",
    DirectDeleteOutsideScope[045] => "direct delete outside scope",
});

report!(Warnings(W) {
    WeirdPropertyName[001] => "weird property name",
    UnenclosedNestedExpression[002] => "unenclosed nested expression",
    DtsHeaderInIncludeFile[003] => "`/dts-v1/` header in a dtsi file",
    ChainedLabels[004] => "chained labels",
    MultipleDtsHeaders[005] => "multiple `dts-v1` headers",
});
